events { worker_connections 1024; }

http {
    server {
        listen 80;

        # ----------------------------------------------------
        # MICROSERVICIO 2 (CORE)
        # ----------------------------------------------------
        location /core/ {
            # FastAPI ya maneja el CORS, NGINX solo pasa el tráfico
            proxy_pass https://microservice-2-production-f917.up.railway.app/;
        }

        # ----------------------------------------------------
        # MICROSERVICIO 3 (RAG)
        # ----------------------------------------------------
        location /rag/ {
            # FastAPI ya maneja el CORS, NGINX solo pasa el tráfico
            proxy_pass https://microservice-3-production.up.railway.app/;
        }
    }
}