events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Añadimos cabeceras CORS globales directamente en el Gateway
        add_header 'Access-Control-Allow-Origin' 'https://rag-frontend-tan.vercel.app' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-api-key,Authorization' always;

        # Atrapa las peticiones OPTIONS y responde "OK" al instante para que el navegador no se queje
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://rag-frontend-tan.vercel.app' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-api-key,Authorization' always;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        location /core/ {
            # Usamos las URLs públicas que NUNCA fallan
            proxy_pass https://microservice-2-production-f917.up.railway.app/;
        }

        location /rag/ {
            # Usamos las URLs públicas que NUNCA fallan
            proxy_pass https://microservice-3-production.up.railway.app/;
        }
    }
}