events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /core/ {
            proxy_pass http://microservice-2.railway.internal:8000/;
        }

        location /rag/ {
            proxy_pass http://microservice-3.railway.internal:8001/;
        }
    }
}